nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade: "))
peso = float(input("Digite seu peso: "))
print("Olá, mundo!")
print("Seu nome é:", nome)
print("Sua idade é:", idade)
print("Seu peso é:", peso)